### ISSUE TITLE
use (w)packagist instead of svn for listing and updates

### ISSUE THREAD

**Issue by chuckadams** [aspirepress/AspireSync#33]
Should be _much_ faster and more reliable than 🤬 svn.    It might lag somewhat, but we have lag too, and the packagist API is zippy enough we could check it every 15 minutes or so.   We'll have to do this for regular packagist support anyway.

**Comment by chuckadams** [comment]
This might be viable for packagist, but wpackagist's API is not remotely on par with packagist.  It obviously has enough for composer to work, but I can't get any kind of updates feed like I get with packagist.

**Comment by chuckadams** [comment]
I still cannot find a usable search endpoint on wpackagist of the sort that vanilla packagist has.  Investigation of the outlandishideas/wpackagist codebase reveals little that's useful to us.  Possibly it ships the data to a private packagist instance, but again I can't find any way to browse packages through their endpoint.  Frankly I'm baffled how it even works with composer in the first place.

Publishing via regular packagist is still a worthy goal, but I'm writing wpackagist off for now, so the wp_org origin is still going to use svn for the forseeable future.  We can define a different scope for regular packagist in another issue.  Closing this one.

**Comment by asirota** [comment]
That's too bad. I guess not too much effort went into it so far.
