### ISSUE TITLE
Build fails when AWS_ECR_REGISTRY is empty

### ISSUE THREAD

**Issue by stardothosting** [aspirepress/AspireSync#5]
The Makefile is expecting this variable to be populated however a dependency on using AWS ECR shouldn't be a blocker on building 

`mkdir -p ./build && \
cp -r ./code/config ./code/src ./code/assetgrabber ./code/composer.* ./build && \
docker build --target prodbuild -t assetgrabber -t :dev:staging-build -t :latest -f ./docker/Dockerfile . && \
rm -fr ./build
[+] Building 0.0s (0/0)                                                                                                                                                   docker:default
ERROR: invalid tag ":dev:staging-build": invalid reference format
make: *** [Makefile:23: build] Error 1
`

**Comment by sarah-savage** [comment]
You should now be able to run `make build-dev` without ECR registry config coming into play.
